apiVersion: apps/v1
kind: Deployment
metadata:
  name: $DFCN
  namespace: $NAMESPACE
  labels:
    app: $DFCN
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $DFCN
  template:
    metadata:
      labels:
        app: $DFCN
    spec:
      containers:
      - name: $DFCN
        image: nexus.colvir.ru/colvir-ms/$DFCN:$COMTAG
        imagePullPolicy: Always
        ports:
          - containerPort: 3002
      imagePullSecrets:
      - name: $SECRET